name: Deploy to GitHub pages
on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          cname: zardoy.com
        env:
          VITE_REDIRECTS: ${{ secrets.VITE_REDIRECTS }}
