name: Deploy to GitHub pages
on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
        env:
          VITE_REDIRECTS: ${{ secrets.VITE_REDIRECTS }}
          VITE_BATTLE_TAG: ${{ vars.VITE_BATTLE_TAG }}
      # - run: pnpm test
      - run: mv dist/index.html dist/404.html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          cname: zardoy.com
